import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import ReactQueryClientProvider from "@/lib/ReactQueryClientProvider";
import { cookies } from "next/headers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const isDarkMode = cookies().get("dark")?.value === "1" ? "dark" : "";
  return (
    <html className="h-full" lang="en">
      <ReactQueryClientProvider>
        <body
          className={`${inter.className} ${isDarkMode} h-fill-available grid grid-rows-[auto_1fr] gap-2 bg-fill-3 text-sm text-primary md:text-base`}
        >
          <Header />
          <main className="relative px-2">{children}</main>
          <Footer />
        </body>
      </ReactQueryClientProvider>
    </html>
  );
}
