import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./(index)/components/Header";
import { ThemeProvider } from "./(index)/components/ThemeProvider";
import ReactQueryClientProvider from "../lib/react-query";
import Footer from "./(index)/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full" lang="en">
      <ReactQueryClientProvider>
        <ThemeProvider>
          <body
            className={`${inter.className} h-fill-available grid grid-rows-[auto_1fr] gap-2 bg-fill-3 text-sm text-primary md:text-base`}
          >
            <Header />
            <main className="px-2 relative">{children}</main>
            <Footer />
          </body>
        </ThemeProvider>
      </ReactQueryClientProvider>
    </html>
  );
}
